org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
mod_version=1.0.0
mod_id=archwood_good

minecraft_version=1.21.1
parchment_version=2024.07.28
minecraft_version_range=[1.21)

neo_version=21.1.218
neo_version_range=[21.0,)
loader_version_range=[2,)

# MAIN DEPENDENCIES
# Get the correct version @ https://maven.blamejared.com/com/hollingsworth/ars_nouveau/ars_nouveau-1.21.1/
nouveau_version=5.10.0.1183
# Get the correct version @ https://maven.blamejared.com/com/alexthw/ars_elemental/ars_elemental-1.21.1/
elemental_version=0.7.6.9.114

# Get the correct version @ https://registry.somethingcatchy.net/#browse/search/generic=keyword%3Dmoonlight
moonlight_version = 1.21-2.29.3
# Get the correct version @ https://registry.somethingcatchy.net/#browse/search/generic=keyword%3Deverycomp
everycomp_version = 1.21-2.11.20
# Get the correct version @ https://registry.somethingcatchy.net/#browse/search/generic=keyword%3Dsupplementaries
supplementaries_version = 1.21-3.5.11

# Get the correct version @ https://maven.createmod.net/com/simibubi/create/
create_version = 6.0.8-169
# Get the correct version @ https://maven.createmod.net/dev/engine-room/flywheel/
flywheel_version = 1.0.5-32
# Get the correct version @ https://maven.createmod.net/net/createmod/ponder/
ponder_version = 1.0.69
# Get the correct version @ https://maven.tterrag.com/com/tterrag/registrate/Registrate/
registrate_version = MC1.21-1.3.0+62

# TOOLS
jei_version=19.10.0.126
# Get the correct version @ https://www.curseforge.com/minecraft/mc-mods/emi/files/all?page=1&pageSize=20&version=1.21.1
emi_version = 1.1.22

# DEPENDENCIES
curios_version=9.0.14+1.21.1
geckolib_version=4.6.6
patchouli_version=87-NEOFORGE-SNAPSHOT
caelus_version=7.0.0+1.21
